/**
 * When editing your questions pay attention to your punctuation.
 * Make sure you use question marks.
 * Make sure the first answer is the correct one.
 * Set at least ANSWER_COUNT answers, any extras will be shuffled in.
 */
export const COUNTRY_CAPITAL_EN_US = [
  { Afghanistan: ["Kabul"] },
  { Albania: ["Tirana"] },
  { Algeria: ["Algiers"] },
  { Andorra: ["Andorra la Vella"] },
  { Angola: ["Luanda"] },
  { "Antigua and Barbuda": ["Saint John's"] },
  { Argentina: ["Buenos Aires"] },
  { Armenia: ["Yerevan"] },
  { Australia: ["Canberra"] },
  { Austria: ["Vienna"] },
  { Azerbaijan: ["Baku"] },
  { "The Bahamas": ["Nassau"] },
  { Bahrain: ["Manama"] },
  { Bangladesh: ["Dhaka"] },
  { Barbados: ["Bridgetown"] },
  { Belarus: ["Minsk"] },
  { Belgium: ["Brussels"] },
  { Belize: ["Belmopan"] },
  { Benin: ["Porto-Novo"] },
  { Bhutan: ["Thimphu"] },
  { Bolivia: ["La Paz", "Sucre"] },
  { "Bosnia and Herzegovina": ["Sarajevo"] },
  { Botswana: ["Gaborone"] },
  { Brazil: ["Brasilia"] },
  { Brunei: ["Bandar Seri Begawan"] },
  { Bulgaria: ["Sofia"] },
  { "Burkina Faso": ["Ouagadougou"] },
  { Burundi: ["Bujumbura"] },
  { Cambodia: ["Phnom Penh"] },
  { Cameroon: ["Yaounde"] },
  { Canada: ["Ottawa"] },
  { "Cape Verde": ["Praia"] },
  { "Central African Republic": ["Bangui"] },
  { Chad: ["N'Djamena"] },
  { Chile: ["Santiago"] },
  { China: ["Beijing"] },
  { Colombia: ["Bogota"] },
  { Comoros: ["Moroni"] },
  { "Republic of the Congo": ["Brazzaville"] },
  { "Democratic Republic of the Congo": ["Kinshasa"] },
  { "Costa Rica": ["San Jose"] },
  { "Cote d'Ivoire": ["Yamoussoukro", "Abidjan"] },
  { Croatia: ["Zagreb"] },
  { Cuba: ["Havana"] },
  { Cyprus: ["Nicosia"] },
  { "Czech Republic": ["Prague"] },
  { Denmark: ["Copenhagen"] },
  { Djibouti: ["Djibouti"] },
  { Dominica: ["Roseau"] },
  { "Dominican Republic": ["Santo Domingo"] },
  { "East Timor": ["Dili"] },
  { Ecuador: ["Quito"] },
  { Egypt: ["Cairo"] },
  { "El Salvador": ["San Salvador"] },
  { "Equatorial Guinea": ["Malabo"] },
  { Eritrea: ["Asmara"] },
  { Estonia: ["Tallinn"] },
  { Ethiopia: ["Addis Ababa"] },
  { Fiji: ["Suva"] },
  { Finland: ["Helsinki"] },
  { France: ["Paris"] },
  { Gabon: ["Libreville"] },
  { "The Gambia": ["Banjul"] },
  { Georgia: ["Tbilisi"] },
  { Germany: ["Berlin"] },
  { Ghana: ["Accra"] },
  { Greece: ["Athens"] },
  { Grenada: ["Saint George's"] },
  { Guatemala: ["Guatemala City"] },
  { Guinea: ["Conakry"] },
  { "Guinea-Bissau": ["Bissau"] },
  { Guyana: ["Georgetown"] },
  { Haiti: ["Port-au-Prince"] },
  { Honduras: ["Tegucigalpa"] },
  { Hungary: ["Budapest"] },
  { Iceland: ["Reykjavik"] },
  { India: ["New Delhi"] },
  { Indonesia: ["Jakarta"] },
  { Iran: ["Tehran"] },
  { Iraq: ["Baghdad"] },
  { Ireland: ["Dublin"] },
  { Israel: ["Jerusalem"] },
  { Italy: ["Rome"] },
  { Jamaica: ["Kingston"] },
  { Japan: ["Tokyo"] },
  { Jordan: ["Amman"] },
  { Kazakhstan: ["Astana"] },
  { Kenya: ["Nairobi"] },
  { Kiribati: ["Tarawa Atoll"] },
  { "North Korea": ["Pyongyang"] },
  { "South Korea": ["Seoul"] },
  { Kosovo: ["Pristina"] },
  { Kuwait: ["Kuwait City"] },
  { Kyrgyzstan: ["Bishkek"] },
  { Laos: ["Vientiane"] },
  { Latvia: ["Riga"] },
  { Lebanon: ["Beirut"] },
  { Lesotho: ["Maseru"] },
  { Liberia: ["Monrovia"] },
  { Libya: ["Tripoli"] },
  { Liechtenstein: ["Vaduz"] },
  { Lithuania: ["Vilnius"] },
  { Luxembourg: ["Luxembourg"] },
  { Macedonia: ["Skopje"] },
  { Madagascar: ["Antananarivo"] },
  { Malawi: ["Lilongwe"] },
  { Malaysia: ["Kuala Lumpur"] },
  { Maldives: ["Male"] },
  { Mali: ["Bamako"] },
  { Malta: ["Valletta"] },
  { "Marshall Islands": ["Majuro"] },
  { Mauritania: ["Nouakchott"] },
  { Mauritius: ["Port Louis"] },
  { Mexico: ["Mexico City"] },
  { "Federated States of Micronesia": ["Palikir"] },
  { Moldova: ["Chisinau"] },
  { Monaco: ["Monaco"] },
  { Mongolia: ["Ulaanbaatar"] },
  { Montenegro: ["Podgorica"] },
  { Morocco: ["Rabat"] },
  { Mozambique: ["Maputo"] },
  { Myanmar: ["Naypyidaw", "Nay Pyi Taw"] },
  { Namibia: ["Windhoek"] },
  { Nauru: ["Yaren"] },
  { Nepal: ["Kathmandu"] },
  { Netherlands: ["Amsterdam"] },
  { "New Zealand": ["Wellington"] },
  { Nicaragua: ["Managua"] },
  { Niger: ["Niamey"] },
  { Nigeria: ["Abuja"] },
  { Norway: ["Oslo"] },
  { Oman: ["Muscat"] },
  { Pakistan: ["Islamabad"] },
  { Palau: ["Melekeok"] },
  { Panama: ["Panama City"] },
  { "Papua New Guinea": ["Port Moresby"] },
  { Paraguay: ["Asuncion"] },
  { Peru: ["Lima"] },
  { Philippines: ["Manila"] },
  { Poland: ["Warsaw"] },
  { Portugal: ["Lisbon"] },
  { Qatar: ["Doha"] },
  { Romania: ["Bucharest"] },
  { Russia: ["Moscow"] },
  { Rwanda: ["Kigali"] },
  { "Saint Kitts and Nevis": ["Basseterre"] },
  { "Saint Lucia": ["Castries"] },
  { "Saint Vincent and the Grenadines": ["Kingstown"] },
  { Samoa: ["Apia"] },
  { "San Marino": ["San Marino"] },
  { "Sao Tome and Principe": ["Sao Tome"] },
  { "Saudi Arabia": ["Riyadh"] },
  { Senegal: ["Dakar"] },
  { Serbia: ["Belgrade"] },
  { Seychelles: ["Victoria"] },
  { "Sierra Leone": ["Freetown"] },
  { Singapore: ["Singapore"] },
  { Slovakia: ["Bratislava"] },
  { Slovenia: ["Ljubljana"] },
  { "Solomon Islands": ["Honiara"] },
  { Somalia: ["Mogadishu"] },
  { "South Africa": ["Pretoria", "Cape Town", "Bloemfontein"] },
  { "South Sudan": ["Juba"] },
  { Spain: ["Madrid"] },
  { "Sri Lanka": ["Colombo", "Sri Jayewardenepura Kotte"] },
  { Sudan: ["Khartoum"] },
  { Suriname: ["Paramaribo"] },
  { Swaziland: ["Mbabane"] },
  { Sweden: ["Stockholm"] },
  { Switzerland: ["Bern"] },
  { Syria: ["Damascus"] },
  { Taiwan: ["Taipei"] },
  { Tajikistan: ["Dushanbe"] },
  { Tanzania: ["Dar es Salaam", "Dodoma"] },
  { Thailand: ["Bangkok"] },
  { Togo: ["Lome"] },
  { Tonga: ["Nuku'alofa"] },
  { "Trinidad and Tobago": ["Port-of-Spain"] },
  { Tunisia: ["Tunis"] },
  { Turkey: ["Ankara"] },
  { Turkmenistan: ["Ashgabat"] },
  { Tuvalu: ["Funafuti"] },
  { Uganda: ["Kampala"] },
  { Ukraine: ["Kyiv"] },
  { "United Arab Emirates": ["Abu Dhabi"] },
  { "United Kingdom": ["London"] },
  { "United States of America": ["Washington D.C."] },
  { Uruguay: ["Montevideo"] },
  { Uzbekistan: ["Tashkent"] },
  { Vanuatu: ["Port-Vila"] },
  { "Vatican City": ["Vatican City"] },
  { Venezuela: ["Caracas"] },
  { Vietnam: ["Hanoi"] },
  { Yemen: ["Sanaa"] },
  { Zambia: ["Lusaka"] },
  { Zimbabwe: ["Harare"] }
];
export const COUNTRY_CAPITAL_DE_DE = [
  { Afghanistan: ["Kabul"] },
  { Albanien: ["Tirana"] },
  { Algerien: ["Algier"] },
  { Andorra: ["Andorra la Vella"] },
  { Angola: ["Luanda"] },
  { "Antigua und Barbuda": ["St. John's"] },
  { Argentinien: ["Buenos Aires"] },
  { Armenien: ["Eriwan"] },
  { Australien: ["Canberra"] },
  { Österreich: ["Wien"] },
  { Aserbaidschan: ["Baku"] },
  { "Die Bahamas": ["Nassau"] },
  { Bahrain: ["Manama"] },
  { Bangladesch: ["Dhaka"] },
  { Barbados: ["Bridgetown"] },
  { Weißrussland: ["Minsk"] },
  { Belgien: ["Brüssel"] },
  { Belize: ["Belmopan"] },
  { Benin: ["Porto-Novo"] },
  { Bhutan: ["Thimphu"] },
  { Bolivien: ["La Paz", "Sucre"] },
  { "Bosnien und Herzegowina": ["Sarajevo"] },
  { Botswana: ["Gaborone"] },
  { Brasilien: ["Brasilia"] },
  { Brunei: ["Bandar Seri Begawan"] },
  { Bulgarien: ["Sofia"] },
  { "Burkina Faso": ["Ouagadougou"] },
  { Burundi: ["Bujumbura"] },
  { Kambodscha: ["Phnom Penh"] },
  { Kamerun: ["Jaunde"] },
  { Kanada: ["Ottawa"] },
  { "Kap Verde": ["Praia"] },
  { "Zentralafrikanische Republik": ["Bangui"] },
  { Tschad: ["N'Djamena"] },
  { Chile: ["Santiago"] },
  { China: ["Peking"] },
  { Kolumbien: ["Bogota"] },
  { Komoren: ["Moroni"] },
  { "Republik Kongo": ["Brazzaville"] },
  { "Demokratische Republik Kongo": ["Kinshasa"] },
  { "Costa Rica": ["San Jose"] },
  { Elfenbeinküste: ["Yamoussoukro", "Abidjan"] },
  { Kroatien: ["Zagreb"] },
  { Kuba: ["Havanna"] },
  { Zypern: ["Nikosia"] },
  { "Tschechische Republik": ["Prag"] },
  { Dänemark: ["Kopenhagen"] },
  { Dschibuti: ["Dschibuti"] },
  { Dominica: ["Roseau"] },
  { "Dominikanische Republik": ["Santo Domingo"] },
  { Osttimor: ["Dili"] },
  { Ecuador: ["Quito"] },
  { Ägypten: ["Kairo"] },
  { "El Salvador": ["San Salvador"] },
  { Äquatorialguinea: ["Malabo"] },
  { Eritrea: ["Asmara"] },
  { Estland: ["Tallinn"] },
  { Äthiopien: ["Addis Abeba"] },
  { Fidschi: ["Suva"] },
  { Finnland: ["Helsinki"] },
  { Frankreich: ["Paris"] },
  { Gabun: ["Libreville"] },
  { "Das Gambia": ["Banjul"] },
  { Georgien: ["Tiflis"] },
  { Deutschland: ["Berlin"] },
  { Ghana: ["Accra"] },
  { Griechenland: ["Athen"] },
  { Grenada: ["St. George's"] },
  { Guatemala: ["Guatemala-Stadt"] },
  { Guinea: ["Conakry"] },
  { "Guinea-Bissau": ["Bissau"] },
  { Guyana: ["Georgetown"] },
  { Haiti: ["Port-au-Prince"] },
  { Honduras: ["Tegucigalpa"] },
  { Ungarn: ["Budapest"] },
  { Island: ["Reykjavik"] },
  { Indien: ["Neu-Delhi"] },
  { Indonesien: ["Jakarta"] },
  { Iran: ["Teheran"] },
  { Irak: ["Bagdad"] },
  { Irland: ["Dublin"] },
  { Israel: ["Jerusalem"] },
  { Italien: ["Rom"] },
  { Jamaika: ["Kingston"] },
  { Japan: ["Tokio"] },
  { Jordanien: ["Amman"] },
  { Kasachstan: ["Astana"] },
  { Kenia: ["Nairobi"] },
  { Kiribati: ["Tarawa-Atoll"] },
  { Nordkorea: ["Pjöngjang"] },
  { Südkorea: ["Seoul"] },
  { Kosovo: ["Pristina"] },
  { Kuwait: ["Kuwait-Stadt"] },
  { Kirgisistan: ["Bischkek"] },
  { Laos: ["Vientiane"] },
  { Lettland: ["Riga"] },
  { Libanon: ["Beirut"] },
  { Lesotho: ["Maseru"] },
  { Liberia: ["Monrovia"] },
  { Libyen: ["Tripolis"] },
  { Liechtenstein: ["Vaduz"] },
  { Litauen: ["Vilnius"] },
  { Luxemburg: ["Luxemburg"] },
  { Mazedonien: ["Skopje"] },
  { Madagaskar: ["Antananarivo"] },
  { Malawi: ["Lilongwe"] },
  { Malaysia: ["Kuala Lumpur"] },
  { Malediven: ["männlich"] },
  { Mali: ["Bamako"] },
  { Malta: ["Valletta"] },
  { Marshallinseln: ["Majuro"] },
  { Mauretanien: ["Nouakchott"] },
  { Mauritius: ["Port Louis"] },
  { Mexiko: ["Mexiko-Stadt"] },
  { "Föderierte Staaten von Mikronesien": ["Palikir"] },
  { Moldawien: ["Chisinau"] },
  { Monaco: ["Monaco"] },
  { Mongolei: ["Ulaanbaatar"] },
  { Montenegro: ["Podgorica"] },
  { Marokko: ["Rabat"] },
  { Mosambik: ["Maputo"] },
  { Myanmar: ["Naypyidaw", "Nay Pyi Taw"] },
  { Namibia: ["Windhoek"] },
  { Nauru: ["Yaren"] },
  { Nepal: ["Kathmandu"] },
  { Niederlande: ["Amsterdam"] },
  { Neuseeland: ["Wellington"] },
  { Nicaragua: ["Managua"] },
  { Niger: ["Niamey"] },
  { Nigeria: ["Abuja"] },
  { Norwegen: ["Oslo"] },
  { Oman: ["Muscat"] },
  { Pakistan: ["Islamabad"] },
  { Palau: ["Melekeok"] },
  { Panama: ["Panama-Stadt"] },
  { "Papua-Neuguinea": ["Port Moresby"] },
  { Paraguay: ["Asuncion"] },
  { Peru: ["Lima"] },
  { Philippinen: ["Manila"] },
  { Polen: ["Warschau"] },
  { Portugal: ["Lissabon"] },
  { Katar: ["Doha"] },
  { Rumänien: ["Bukarest"] },
  { Russland: ["Moskau"] },
  { Ruanda: ["Kigali"] },
  { "St. Kitts und Nevis": ["Basseterre"] },
  { "Saint Lucia": ["Castries"] },
  { "St. Vincent und die Grenadinen": ["Kingstown"] },
  { Samoa: ["Apia"] },
  { "San Marino": ["San Marino"] },
  { "Sao Tome und Principe": ["Sao Tome"] },
  { "Saudi-Arabien": ["Riad"] },
  { Senegal: ["Dakar"] },
  { Serbien: ["Belgrad"] },
  { Seychellen: ["Victoria"] },
  { "Sierra Leone": ["Freetown"] },
  { Singapur: ["Singapur"] },
  { Slowakei: ["Bratislava"] },
  { Slowenien: ["Ljubljana"] },
  { Salomonen: ["Honiara"] },
  { Somalia: ["Mogadischu"] },
  { Südafrika: ["Pretoria", "Kapstadt", "Bloemfontein"] },
  { Südsudan: ["Juba"] },
  { Spanien: ["Madrid"] },
  { "Sri Lanka": ["Colombo", "Sri Jayewardenepura Kotte"] },
  { Sudan: ["Khartoum"] },
  { Suriname: ["Paramaribo"] },
  { Swasiland: ["Mbabane"] },
  { Schweden: ["Stockholm"] },
  { Schweiz: ["Bern"] },
  { Syrien: ["Damaskus"] },
  { Taiwan: ["Taipeh"] },
  { Tadschikistan: ["Duschanbe"] },
  { Tansania: ["Dar es Salaam", "Dodoma"] },
  { Thailand: ["Bangkok"] },
  { Togo: ["Lomé"] },
  { Tonga: ["Nuku'alofa"] },
  { "Trinidad und Tobago": ["Hafen von Spanien"] },
  { Tunesien: ["Tunis"] },
  { Türkei: ["Ankara"] },
  { Turkmenistan: ["Aschgabat"] },
  { Tuvalu: ["Funafuti"] },
  { Uganda: ["Kampala"] },
  { Ukraine: ["Kiew"] },
  { "Vereinigte Arabische Emirate": ["Abu Dhabi"] },
  { "Vereinigtes Königreich": ["London"] },
  { "Vereinigte Staaten von Amerika": ["Washington D.C."] },
  { Uruguay: ["Montevideo"] },
  { Usbekistan: ["Taschkent"] },
  { Vanuatu: ["Port-Vila"] },
  { Vatikanstadt: ["Vatikanstadt"] },
  { Venezuela: ["Caracas"] },
  { Vietnam: ["Hanoi"] },
  { Jemen: ["Sanaa"] },
  { Sambia: ["Lusaka"] },
  { Simbabwe: ["Harare"] }
];
